{% set version = "2.4.0" %}

package:
  name: nb_conda_kernels
  version: {{ version }}

source:
  url: https://github.com/Anaconda-Platform/nb_conda_kernels/archive/{{ version }}.tar.gz
  sha256: 0e75a5331a59b9eb6df341b3ac275157d87d7d5689747c46b8ea92e3899aa40c

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - pip
  run:
    - python >=3.8,<3.12
    - pywin32  # [win]
    - jupyter_client >=4.2
    - __unix  # [unix]
    - __win  # [win]

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f ${PREFIX}/bin/.nb_conda_kernels-post-link.sh  # [unix]
    - test -f ${PREFIX}/bin/.nb_conda_kernels-pre-unlink.sh  # [unix]
    - if not exist %PREFIX%\Scripts\.nb_conda_kernels-post-link.bat (exit 1)  # [win]
    - if not exist %PREFIX%\Scripts\.nb_conda_kernels-pre-unlink.bat (exit 1)  # [win]
  imports:
    - nb_conda_kernels

about:
  home: https://github.com/Anaconda-Platform/nb_conda_kernels
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Launch Jupyter kernels for any installed conda environment

extra:
  recipe-maintainers:
    - ocefpaf
    - damianavila
    - mcg1969
